# Generated by Django 4.2.7 on 2025-08-08
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Название категории"),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
            ],
            options={
                "verbose_name": "Категория документа",
                "verbose_name_plural": "Категории документов",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="DocumentTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Название тега"
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#007bff", max_length=7, verbose_name="Цвет тега"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
            ],
            options={
                "verbose_name": "Тег",
                "verbose_name_plural": "Теги",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Заголовок")),
                ("content", models.TextField(verbose_name="Содержимое документа")),
                (
                    "file_path",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="documents/",
                        verbose_name="Файл",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                (
                    "word_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Количество слов"
                    ),
                ),
                (
                    "search_vector",
                    models.TextField(blank=True, verbose_name="Вектор поиска"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Автор",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="doc_storage.documentcategory",
                        verbose_name="Категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "Документ",
                "verbose_name_plural": "Документы",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DocumentTagRelation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tag_relations",
                        to="doc_storage.document",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_relations",
                        to="doc_storage.documenttag",
                    ),
                ),
            ],
            options={
                "verbose_name": "Связь документ-тег",
                "verbose_name_plural": "Связи документов и тегов",
            },
        ),
        migrations.CreateModel(
            name="WordMatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "query",
                    models.CharField(max_length=255, verbose_name="Поисковый запрос"),
                ),
                (
                    "matched_word",
                    models.CharField(max_length=255, verbose_name="Найденное слово"),
                ),
                (
                    "position",
                    models.PositiveIntegerField(verbose_name="Позиция в тексте"),
                ),
                (
                    "context_before",
                    models.CharField(blank=True, max_length=200, verbose_name="Контекст до"),
                ),
                (
                    "context_after",
                    models.CharField(blank=True, max_length=200, verbose_name="Контекст после"),
                ),
                (
                    "match_type",
                    models.CharField(
                        choices=[
                            ("exact", "Точное совпадение"),
                            ("partial", "Частичное совпадение"),
                            ("fuzzy", "Нечеткое совпадение"),
                        ],
                        default="exact",
                        max_length=20,
                        verbose_name="Тип совпадения",
                    ),
                ),
                (
                    "relevance_score",
                    models.FloatField(default=1.0, verbose_name="Релевантность"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата поиска"),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="doc_storage.document",
                        verbose_name="Документ",
                    ),
                ),
            ],
            options={
                "verbose_name": "Найденное слово",
                "verbose_name_plural": "Найденные слова",
                "ordering": ["-relevance_score", "position"],
            },
        ),
        migrations.CreateModel(
            name="SearchHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "query",
                    models.CharField(max_length=255, verbose_name="Поисковый запрос"),
                ),
                (
                    "results_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Количество результатов"
                    ),
                ),
                (
                    "search_time",
                    models.FloatField(default=0.0, verbose_name="Время поиска (сек)"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата поиска"),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP адрес"
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="doc_storage.document",
                        verbose_name="Документ",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "История поиска",
                "verbose_name_plural": "История поисков",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(fields=["title"], name="doc_storage_title_30a4dd_idx"),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["created_at"], name="doc_storage_created_820a36_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["category"], name="doc_storage_categor_3ee17b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["author"], name="doc_storage_author__cc083b_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="documenttagrelation",
            unique_together={("document", "tag")},
        ),
        migrations.AddIndex(
            model_name="wordmatch",
            index=models.Index(fields=["document", "query"], name="doc_storage_wordmat_docque_bf5364_idx"),
        ),
        migrations.AddIndex(
            model_name="wordmatch",
            index=models.Index(fields=["matched_word"], name="doc_storage_wordmat_matched_f134c6_idx"),
        ),
        migrations.AddIndex(
            model_name="wordmatch",
            index=models.Index(fields=["position"], name="doc_storage_wordmat_positio_94b825_idx"),
        ),
        migrations.AddIndex(
            model_name="searchhistory",
            index=models.Index(fields=["query"], name="doc_storage_searchhi_query_381a55_idx"),
        ),
        migrations.AddIndex(
            model_name="searchhistory",
            index=models.Index(
                fields=["created_at"], name="doc_storage_searchhi_created_120848_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="searchhistory",
            index=models.Index(fields=["user"], name="doc_storage_searchhi_user_id_87d63c_idx"),
        ),
        migrations.AddIndex(
            model_name="searchhistory",
            index=models.Index(fields=["document"], name="doc_storage_searchhi_documen_a4cbcf_idx"),
        ),
    ]