# Generated by Django 4.2.7 on 2025-08-07 21:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("doc_storage", "0003_update_searchhistory"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="searchhistory",
            new_name="doc_storage_documen_a4cbcf_idx",
            old_name="doc_storage_search_doc_idx",
        ),
        migrations.RenameIndex(
            model_name="wordmatch",
            new_name="doc_storage_documen_bf5364_idx",
            old_name="doc_storage_word_match_doc_query_idx",
        ),
        migrations.RenameIndex(
            model_name="wordmatch",
            new_name="doc_storage_matched_f134c6_idx",
            old_name="doc_storage_word_match_word_idx",
        ),
        migrations.RenameIndex(
            model_name="wordmatch",
            new_name="doc_storage_positio_94b825_idx",
            old_name="doc_storage_word_match_pos_idx",
        ),
    ]
